config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    member do
      post :favorite
      post :unfavorite
    end

    member do
      post :like
      post :unlike
    end

    member do
      post :friend
      post :unfriend
    end

    

  end


  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  resources :followships, only: [:create, :destroy]
  
  resources :friendships, only: [:create, :destroy]
  
  resources :categories, only: :show
	root "restaurants#index"
	
	namespace :admin do
		resources :restaurants
    resources :categories
    root "restaurants#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  mount_uploader :avatar, AvatarUploader

  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def friend?(user)
    self.friends.include?(user)
  end

  def all_friend
    (friends + passive_friends).uniq
  end

  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  # 自訂名稱後，Rails 無法自動推論來源名稱，需另加 source 告知 model name
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

   # 「使用者的追蹤者」的設定
   # 透過 class_name, foreign_key 的自訂，指向 Followship 表上的另一側
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :passive_friends, through: :inverse_friendships, source: :user
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user,only:[:show, :edit, :update, :friend_list]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers # 需至 User Model 自訂方法
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)      
    end    
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @friends = @user.all_friend
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="contsicer">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <h3>Edit Profile</h3>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :intro, "自我介紹" %>
          <%= f.text_area :intro, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :avatar, "大頭照上傳" %>
          <%= image_tag @user.avatar if @user.avatar? %>
          <%= f.file_field :avatar %>
        </div>
        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-info" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
        </div>
       <% end %>

    </div>
  </div>
</div>

app/views/users/friend_list.html.erb
<div class="col-md-1"></div>

<div class="col-md-10">
  <div class="comlay">
    <div class="panel panel-default text-center">
      <!-- 顯示已評論餐廳的清單 -->
      <div class="panel-heading">
        <h3 class="panel-title"><strong><%= @friends.count %></strong> friends</h3>
      </div>
          
      <div class="panel-body">
        <% @friends.each do |friend| %>
        <%= link_to user_path(friend) do %>
        <div class="my-restaurant">
          <div>
          <%=image_tag(friend.avatar, height: 60, width: 60, class: "img-circle") %>
            
          </div>
       
          <h5><%= friend.name %></h5>
        </div>
          
        <% end %>
        <% end %>
     
    </div>
  </div>
</div>

<div class="col-md-1"></div>

<style>
    .my-restaurant{
    display: inline-block;
    text-align: center;
    padding: 7px 7px 0 7px;
  }
</style>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h3>美食達人</h3>
      </div>
    </div>
    <% @users.each do |user| %>
      <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
        <%= link_to user_path(user) do %>
        <%= image_tag(user.avatar, class: "img-rounded") %>
        <!-- 會用 POST 動作導向 http://localhost:3000/followships?following_id={user.id} -->
        <h4><%= user.name %></h4>
        <% end %>
        <%= render partial: "shared/follow", locals: {user: user} %>
        <%= render partial: "shared/friend", locals: {user: user} %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="comtainer">
  <div class="row">
    <div class="col-md-10">
      
      <div class="perpage">

        <div class="col-md-4 col-sm-4 col-md-offset-3 ">
          <div class="text-center">
            <%= image_tag @user.avatar, class:"img-responsive img-rounded" %>   
          </div>
        </div>

        <div class="col-md-5 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <ul class="list-unstyled list-inline">
            <li><strong><%= @commented_restaurants.count %></strong> 已評論餐廳 </li>
            <li><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳 </li>
            <li><strong><%= @followings.count %></strong> followings </li>
            <li><strong><%= @followers.count %></strong> follower </li>
          </ul>
          <div><%= simple_format @user.intro %></div>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-warning" %>
            <% end %>
            <%= link_to "Friend List", friend_list_user_path(@user), class: "btn btn-info"%>
          </div>

        <div class="clearfix"></div>

      </div>

      <br>

      

    </div>
  </div>
</div>

<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @followings.count %></strong> followings</h3>
    </div>

    <ul class="list-group">
      <% @followings.each do |following| %>
      <li class="list-group-item">
        <%= link_to user_path(following) do %>
        <%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") %>
        <%= following.name %>
        <% end %>
      </li>
      <% end %>
    </ul>

  </div>
  <!-- 顯示followers的清單，panel包一個list-group  -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @followers.count %></strong> followers</h3>
    </div>
    <ul class="list-group">
      <% @followers.each do |follower| %>
      <li class="list-group-item">
        <%= link_to user_path(follower) do %>
        <%= image_tag(follower.avatar, height: 30, width: 30, class: "img-circle") %>
        <%= follower.name %>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>


</div>

<div class="col-md-8">
  <div class="comlay">
    <div class="panel panel-default text-center">
      <!-- 顯示已評論餐廳的清單 -->
      <div class="panel-heading">
        <h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h3>
      </div>
          
      <div class="panel-body">
        <% @commented_restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant) do %>
          
        <div class="my-restaurant">
          <div>
            <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
            
            </div>
          <h5><%= restaurant.name %></h5>
        </div>
          
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
   <!-- 顯示收藏的餐廳的清單，panel包一個panel-body裡面簡單顯示餐廳圖片和name -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</h3>
    </div>
    <div class="panel-body">
      <% @favorited_restaurants.each do |restaurant| %>
      <div class="my-restaurant">
        <div>
          <%= link_to restaurant_path(restaurant) do %>
            <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
            <h5><%= restaurant.name %></h5>
            <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<style>
  .my-restaurant{
    display: inline-block;
    text-align: center;
    padding: 7px 7px 0 7px;
  }
  .my-restaurant >div{
    height: 60px;
  }
  .my-restaurant img{
    max-height: 100%;
  }
 
  .comlay{
    text-align: center;
    margin: 0 auto;
  }
  
</style>