config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    member do
      post :favorite
      post :unfavorite
    end

    member do
      post :like
      post :unlike
    end

    member do
      post :friend
      post :unfriend
    end

    

  end


  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  resources :followships, only: [:create, :destroy]
  
  resources :friendships, only: [:create, :destroy]
  
  resources :categories, only: :show
	root "restaurants#index"
	
	namespace :admin do
		resources :restaurants
    resources :categories
    root "restaurants#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	mount_uploader :image, PhotoUploader
	validates_presence_of :name

  belongs_to :category

  # 當 Restaurant 物件被刪除時，順便刪除依賴的 Comment
  has_many :comments, dependent: :destroy


  # 自訂名稱後，Rails 無法自動推論來源名稱，需另加 source 告知 model name
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def count_favorite
    self.favorites_count = self.favorites.size
    self.save
  end
    

  def is_liked?(user)
    self.liked_users.include?(user)
  end
  
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :authenticate_admin
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

	def index
		@restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
  	@restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def show
  end

  def update
   if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant)
      flash[:notice] = "restaurant was successfully updated"
   else
      render :edit
      flash[:alert] = "restaurant was failed to update"
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end 

  private

  def set_restaurant
   	@restaurant = Restaurant.find(params[:id]) 	
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end



end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	
	def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  	@comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    @restaurant.count_favorites
    redirect_back(fallback_location: root_path)  # 導回上一頁   
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorite = Favorite.where(restaurant: @restaurant, user: current_user)
    favorite.destroy_all
    @restaurant.count_favorites
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)  # 導回上一頁 
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    like = Like.where(restaurant: @restaurant, user: current_user)
    like.destroy_all
    redirect_back(fallback_location: root_path)
  end
  
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
  <% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul> 
  <% end %>

<div class="container">
  
  <div class="admfosen center-block">
    <%= form_for  [:admin, @restaurant] do |f| %>

    <div class="form-group fosen">
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>         
    </div>
    
    <div class="form-group fosen">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <div class="form-group fosen">
      <%= f.label :tel, "Tel" %>
      <%= f.text_field :tel, class: "form-control" %>
    </div>
    
    <div class="form-group fosen">
      <%= f.label :address, "Address" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    
    <div class="form-group fosen">
      <%= f.label :opening_hours, "Opening Hours" %>
      <%= f.text_field :opening_hours, class: "form-control" %>
    </div>
    
    <div class="form-group fosen">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    
    <div class="filesen">
      <%= f.label :image, "Photo" %>
      <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
      <%= f.file_field :image %>
      </div>
    
    <div>
      <%= f.submit class:'btn btn-info'%>
    </div>
  </div>

</div>

<% end %>


<style type="text/css">
  .fosen{
    width: 400px;
  }
  .filesen{
    float: left;
    margin-right: -20px;
  }
  .admfosen{
    width: 500px;
    padding-left: 50px;
  }


</style>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">
	
	<div class="text-center">
		<h4><%= link_to '+New Restaurant', new_admin_restaurant_path %></h4>
	</div>

	<div class="text-center">
  <%= link_to 'Restaurant', admin_restaurants_path %> |
  <%= link_to 'Categories', admin_categories_path %>
	</div>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>No</th>
				<th>Category</th>
				<th>Name</th>
				<th>Address</th>
				<th>Opening Hours</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>		
	  <% @restaurants.each do |restaurant| %>
	  <tr>
	  	<th scope="row"><%= restaurant.id %></th>
	    <td>[<%= restaurant.category.name %>]</td>
	    <td><%= restaurant.name %></td>
	    <td><%= restaurant.address %></td>
	    <td><%= restaurant.opening_hours %></td>

	    <td><%= link_to 'Show', admin_restaurant_path(restaurant) %></td>
	    <td><%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %></td>
	    <td><%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: {confirm:"Are you sure?"} %></td>
	  </tr>
	  <% end %>
	  
	</table>
		<div class="text-center">
			<%= paginate @restaurants %>
		</div>

</div>

<style type="text/css">


</style>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<div class="container">
	<h1><%= @restaurant.name %></h1>
	<h5><%= @restaurant.category.name %></h5>
	<h5>
		Opening Hours:<%= @restaurant.opening_hours %>
	</h5>
	<h5>
		Tel: <%= @restaurant.tel %>
	</h5>
	<h5>
		Address: <%= @restaurant.address %>
	</h5>
	<h5>
		Description:<%= @restaurant.description %>
	</h5>
	<%= image_tag @restaurant.image, width: '600px' %>
	

	<h5><%= link_to 'Back to index', admin_restaurants_path %>
	</h5>
</div>