config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    member do
      post :favorite
      post :unfavorite
    end

    member do
      post :like
      post :unlike
    end

    member do
      post :friend
      post :unfriend
    end

    

  end


  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  resources :followships, only: [:create, :destroy]
  
  resources :friendships, only: [:create, :destroy]
  
  resources :categories, only: :show
	root "restaurants#index"
	
	namespace :admin do
		resources :restaurants
    resources :categories
    root "restaurants#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  # 如果分類下已有餐廳，就不允許刪除分類（刪除時拋出 Error）
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }
  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :friend_id, uniqueness: { scope: :user_id }
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	mount_uploader :image, PhotoUploader
	validates_presence_of :name

  belongs_to :category

  # 當 Restaurant 物件被刪除時，順便刪除依賴的 Comment
  has_many :comments, dependent: :destroy


  # 自訂名稱後，Rails 無法自動推論來源名稱，需另加 source 告知 model name
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def count_favorite
    self.favorites_count = self.favorites.size
    self.save
  end
    

  def is_liked?(user)
    self.liked_users.include?(user)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  mount_uploader :avatar, AvatarUploader

  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def friend?(user)
    self.friends.include?(user)
  end

  def all_friend
    (friends + passive_friends).uniq
  end

  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  # 自訂名稱後，Rails 無法自動推論來源名稱，需另加 source 告知 model name
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

   # 「使用者的追蹤者」的設定
   # 透過 class_name, foreign_key 的自訂，指向 Followship 表上的另一側
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :passive_friends, through: :inverse_friendships, source: :user
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  @categories = Category.all
  @category = Category.find(params[:id])
  @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
	end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

	private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user,only:[:show, :edit, :update, :friend_list]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers # 需至 User Model 自訂方法
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)      
    end    
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @friends = @user.all_friend
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">
      .alert {
        border: none;
      }
    </style>

  </head>

  <body>


    <nav class="navbar navbar-default">
      <div class="container-fluid">



        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
        </div>

        

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="請輸入關鍵字">
            </div>
            <button type="submit" class="btn btn-default">搜尋</button>
          </form>

          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>
              <% if current_user.admin? %>
                <li><%= link_to 'admin後台',admin_restaurants_path %></li>
              <% end %>
              <li><%= link_to current_user.email %></li>
              <li><%= link_to 'Profile', user_path(current_user) %></li>
              <li ><%= link_to('登出', destroy_user_session_path, method: :delete) %> <span class="sr-only">(current)</span></li>
              <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
              <li><%= link_to('註冊', new_user_registration_path) %><span class="sr-only">(current)</span></li>
              <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %> 
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->

    </nav>
        <% if flash[:notice] %>
        <div class="container">
          <div class="row">
            <div class="alert alert-success text-center">
              <%= notice %>
            </div>
          </div>
        </div>
        <% end %>

        <% if flash[:alert] %>
        <div class="container">
          <div class="row">
            <div class="alert alert-danger text-center">
              <%= alert %>
            </div>
          </div>
        </div>
        <% end %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-default" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user)%>
    <%= link_to 'Unfollow', followship_path(user), method: :delete, class: "btn btn-default" %>
  <% else %>
    <%= link_to 'Follow', followships_path(following_id: user), method: :post, class: "btn btn-info" %>
  <% end %>
<% end %>

app/views/shared/_friend.html.erb
<% if user != current_user %>
  <% if current_user.friend?(user)%>
    <%= link_to 'Unfriend', friendship_path(user), method: :delete, class: "btn btn-default" %>
  <% else %>
    <%= link_to 'Friend', friendships_path(friend_id: user), method: :post, class: "btn btn-info" %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if restaurant.is_liked?(current_user) %>
  <%= link_to "Unlike", unlike_restaurant_path(restaurant), method: :post, class: "btn btn-default" %>
<% else %>
  <%= link_to "Like", like_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-4">
        <div class="restaurant-item">
          <%= image_tag restaurant.image, class: "img-responsive center-block" %>
          
          <div class="caption">
            <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
            <p class="label label-primary"><%= restaurant.category.name %><p>
            <p><%= truncate(restaurant.description, length: 80) %></p>
            <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
            <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
          </div>
          
        </div>
      </div>

    <% end %>
    
    <div class="text-center">
      <%= paginate @restaurants %>
    </div>